### ISSUE TITLE
关于 Android 更换 core 的问题

### ISSUE THREAD

**Issue by AkinoKaede** [XTLS/X-flutter#3]
#1 中描述如下:
>  何况 X-flutter 本身就预计不会上架，因为我的设计是安卓端也可以自行换 core，而 Play Store 不允许这样做

我从其他开发者处获悉，此行为在 API 29 (Android 10) 后便不被允许。不能上架 Play Store 的原因是否是因为 Google Play 目前要求应用 API 版本最低为 29？

Android Developers 在 [*Behavior changes: apps targeting API 29+*](https://developer.android.com/about/versions/10/behavior-changes-10) 中写到
> Untrusted apps that target Android 10 cannot invoke `exec()` on files within the app's home directory. 

那么这样的设计是否意味在 X-flutter 将一直使用 API 28，它在现在就被认为已经过时，更不用谈未来。

@rprx

**Comment by SekiBetu** [comment]
与 Termux 共命运

**Comment by rprx** [comment]
**实现方式是热更新 Xray-core 这个 SO 库，不是 Termux 那种。**

不会上架是因为 Play Store 不收带热更新的 APP，我也没有兴趣去为此注册一个开发者账号。

**Comment by AkinoKaede** [comment]
> **实现方式是热更新 Xray-core 这个 SO 库，不是 Termux 那种。**
> 
> 不会上架是因为 Play Store 不收带热更新的 APP，我也没有兴趣去为此注册一个开发者账号。

OK，感谢解答

**Comment by rurirei** [comment]
**do executable files inside data dir** is not allowed on Android 10 and above, as takes shadowsocks-android liblocal.so a example.

i'm agreed with the restriction.

**Comment by rprx** [comment]
@rurirei APP 应该仍可以更新已有的 SO 库等，例如 [tinker](https://github.com/Tencent/tinker)，此外，其实可以手动替换 APK 中和手机中的 SO 文件
